dashboard:
  grafana_influxdb:
    datasource: influxdb
    format: json
    template: grafana/files/grafana_dashboards/grafana_influxdb.json
  grafana_prometheus:
    datasource: prometheus
    format: json
    template: grafana/files/grafana_dashboards/grafana_prometheus.json
  main:
    datasource: influxdb
    format: yaml
    base_dashboards: ['grafana:client:base_templates:main_dashboard']
    base_rows: ['grafana:client:base_templates:service_row']
    base_panels: ['grafana:client:base_templates:cluster_status_singlestat']
  service_level:
    datasource: influxdb
    format: yaml
    base_dashboards: ['grafana:client:base_templates:service_level_dashboard']
    base_rows: ['grafana:client:base_templates:service_level_row']
    base_panels: ['grafana:client:base_templates:service_level_piechart']
