{%- from "grafana/map.jinja" import server with context %}
doc:
  name: Grafana
  description: A beautiful, easy to use and feature rich Graphite dashboard replacement and graph editor.
  role:
    server:
      name: server
      param:
        bind:
          name: Network bind
          value: {{ server.bind.host }}:{{ server.bind.port }}
      endpoint:
        grafana_server:
          name: default
          type: grafana_server
          address: http://{{ server.bind.host }}:{{ server.bind.port }}/
          protocol: http